[profile.release]
panic = 'unwind'

[workspace]
members = [
    "node",
    "runtime/arctic",
    "runtime/frost",
    "pallets/airdrop",
    "pallets/fees-split",
    "pallets/simple-inflation",
    "integration-tests",
]

