name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-project: 
    name: Build project
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@master
      with:
        submodules: true
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2022-01-16
        override: true
        target: wasm32-unknown-unknown
    - name: Test and Build optimized binary
      run: |
        rustup show
        cargo --version
        rustc --version
        cargo test --verbose --workspace
        cargo clean
          cargo build --release
    - uses: actions/upload-artifact@v2
      with:
        name: ice-node
        path: target/release/ice-node
