name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-project: 
    name: Build project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install rust dependencies
      run: |
        scripts/init.sh
        cargo --version
        rustc --version
        cargo +$WASM_BUILD_TOOLCHAIN --version
        rustc +$WASM_BUILD_TOOLCHAIN --version
      env:
        WASM_BUILD_TOOLCHAIN: nightly-2022-01-16
    - name: Checkout the source code
      uses: actions/checkout@master
      with:
        submodules: true
    - name: Check targets are installed correctly
      run: rustup target list --installed
    - name: Run all tests
      run: cargo test --all
    - name: Cleanup after tests
      run: cargo clean
    - name: Build optimized binary
      run: cargo build --release
    - uses: actions/upload-artifact@v2
      with:
        name: ice-node
        path: target/release/ice-node