name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: Check to latest commit
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2022-01-16
          components: rustfmt
          target: wasm32-unknown-unknown
          default: true
      - name: Check All
        run: make check-all
      - name: Test All
        run: |
          make test-all
      - name: clean runner workspace
        run: |
          rm -r *
