name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-project: 
    name: Build project
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@master
      with:
        submodules: true
    - name: Test and Build optimized binary
      run: |
        sudo apt update
        sudo apt install -y git clang curl libssl-dev llvm libudev-dev build-essential
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        source $HOME/.cargo/env
        rustup toolchain add nightly-2022-01-16
        rustup default nightly-2022-01-16
        rustup target add wasm32-unknown-unknown --toolchain nightly-2022-01-16
        rustup show
        cargo --version
        rustc --version
        cargo test --all
        cargo clean
        cargo build --release
    - uses: actions/upload-artifact@v2
      with:
        name: ice-node
        path: target/release/ice-node
