name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-project:
    name: Build project
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2022-01-16
        target: x86_64-unknown-linux-gnu
        components: rustfmt, clippy
        default: true
    - name: Install WASM target (for runtime building)
      shell: bash
      run: rustup target add wasm32-unknown-unknown --toolchain nightly-2022-01-16
    - name: Build optimized binary
      run: cargo build --quiet

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-10-27
          components: clippy
      - name: Run clippy
        run: cargo clippy -- -D warnings

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run cargofmt
        run: cargo +stable fmt --all -- --check
