name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-project: 
    name: Build project
    runs-on:
      - self-hosted
      - ubuntu-20.4
    steps:
    - name: Checkout the source code
      uses: actions/checkout@master
      with:
        submodules: true
    - name: Install rust dependencies
      run: |
        sudo apt update
        sudo apt install -y git clang curl libssl-dev llvm libudev-dev
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        source $HOME/.cargo/env
        rustup default stable
        rustup update
        rustup update nightly
        rustup target add wasm32-unknown-unknown --toolchain nightly
        rustup show
        rustup update
        rustup update nightly
        rustup target add wasm32-unknown-unknown --toolchain nightly
        cargo --version
        rustc --version
        cargo +$WASM_BUILD_TOOLCHAIN --version
        rustc +$WASM_BUILD_TOOLCHAIN --version
      env:
        WASM_BUILD_TOOLCHAIN: nightly-2022-01-16
    
    
    - name: Run all tests
      run: cargo test --all
    - name: Cleanup after tests
      run: cargo clean
    - name: Build optimized binary
      run: cargo build --release
    - uses: actions/upload-artifact@v2
      with:
        name: ice-node
        path: target/release/ice-node
