name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-project:
    name: Cargo test
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-01-16
          override: true
          target: wasm32-unknown-unknown
      - name: Install build-essentials
        run: sudo apt install -y curl build-essential cmake pkg-config libssl-dev openssl git clang libclang-dev
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Run cargo tests
        run: cargo test --verbose --workspace
      - name: Build optimized binary
        run: |
          cargo clean
          cargo build --release
      - uses: actions/upload-artifact@v2
        with:
          name: ice-node
          path: target/release/ice-node
