name: Release
on:
   workflow_dispatch:
     inputs:
      srtool_tag:
        description: The SRTOOL tag to use
        default: 1.57.0
        required: false
      ref:
        description: The ref to be used for the repo
        default: main
        required: false
jobs:
  build-runtime:
    runs-on: ubuntu-latest
    env:
      SUBWASM_VERSION: 0.15.0
    strategy:
      matrix:
        chain: ["arctic"]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Srtool build
        id: srtool_build
        uses: chevdor/srtool-actions@v0.3.0
        with:
          chain: ${{ matrix.chain }}
          tag: ${{ github.event.inputs.srtool_tag || env.SRTOOL_TAG }}

      - name: Summary
        shell: bash
        run: |
          echo '${{ steps.srtool_build.outputs.json }}' | jq > ${{ matrix.chain }}-srtool-digest.json
          cat ${{ matrix.chain }}-srtool-digest.json
          echo "Compact Runtime: ${{ steps.srtool_build.outputs.wasm }}"
          echo "Compressed Runtime: ${{ steps.srtool_build.outputs.wasm_compressed }}"
      - name: Archive Artifacts for ${{ matrix.chain }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.chain }}-runtime
          path: |
            ${{ steps.srtool_build.outputs.wasm }}
            ${{ steps.srtool_build.outputs.wasm_compressed }}
            ${{ matrix.chain }}-srtool-digest.json
      - name: Install subwasm
        shell: bash
        run: |
          wget https://github.com/chevdor/subwasm/releases/download/v${{ env.SUBWASM_VERSION }}/subwasm_linux_amd64_v${{ env.SUBWASM_VERSION }}.deb
          sudo dpkg -i subwasm_linux_amd64_v${{ env.SUBWASM_VERSION }}.deb
          subwasm --version
      - name: Show Runtime information
        shell: bash
        run: |
          subwasm info ${{ steps.srtool_build.outputs.wasm }}
          subwasm info ${{ steps.srtool_build.outputs.wasm_compressed }}
          subwasm --json info ${{ steps.srtool_build.outputs.wasm }} > ${{ matrix.chain }}-info.json
          subwasm --json info ${{ steps.srtool_build.outputs.wasm_compressed }} > ${{ matrix.chain }}-compressed-info.json
      - name: Extract the metadata
        shell: bash
        run: |
          subwasm meta ${{ steps.srtool_build.outputs.wasm }}
          subwasm --json meta ${{ steps.srtool_build.outputs.wasm }} > ${{ matrix.chain }}-metadata.json
      - name: Check the metadata diff
        shell: bash
        run: |
          subwasm diff ${{ steps.srtool_build.outputs.wasm }} --chain-b ${{ matrix.chain }} || \
            echo "Subwasm call failed, check the logs. This is likely because ${{ matrix.chain }} is not known by subwasm" | \
            tee ${{ matrix.chain }}-diff.txt
      - name: Archive Subwasm results
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.chain }}-runtime
          path: |
            ${{ matrix.chain }}-info.json
            ${{ matrix.chain }}-compressed-info.json
            ${{ matrix.chain }}-metadata.json
            ${{ matrix.chain }}-diff.txt
  build-binary:
    name: Build binary
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        target:
        - x86_64-unknown-linux-gnu
        - aarch64-unknown-linux-gnu

    steps:
    - name: Checkout the source code
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install ARM64 multilib
      if: contains(matrix.target, 'aarch64')
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-multilib g++-multilib
        sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
        mkdir .cargo
        printf '[target.aarch64-unknown-linux-gnu]\nlinker = "aarch64-linux-gnu-gcc"' > .cargo/config
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2022-01-16
        target: ${{ matrix.target }}
        components: rustfmt, clippy
        default: true

    - name: Install WASM target (for runtime building)
      shell: bash
      run: rustup target add wasm32-unknown-unknown --toolchain nightly-2022-01-16

    - name: Build optimized binary
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --locked --target ${{ matrix.target }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@master
      with:
        name: ${{ matrix.target }}
        path: target/${{ matrix.target }}/release/ice-node

  release:
    name: Release
    needs:
    - build-binary
    - build-runtime
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the source code
      uses: actions/checkout@v2

    - id: get_version
      uses: battila7/get-version-action@v2

    - name: Create dir
      shell: bash
      run: |
        mkdir -p release/tmp/
        cd release/tmp/
        mkdir  arctic x86_64 aarch64
    - name: get x86_64 binary
      uses: actions/download-artifact@v2
      with:
        name: x86_64-unknown-linux-gnu
        path: release/tmp/x86_64/

    - name: get aarch64 binary
      uses: actions/download-artifact@v2
      with:
        name: aarch64-unknown-linux-gnu
        path: release/tmp/aarch64/

    - uses: actions/download-artifact@v2
      with:
        name: main-runtime
        path: release/tmp/arctic/

    - id: compress_artifacts
      shell: bash
      run: |
        cd release/
        echo "::set-output name=main::$(jq -r '.core_version' tmp/arctic/main-info.json | awk '{print $1}')"
        chmod +x tmp/x86_64/arctic tmp/aarch64/arctic
        tar -czvf arctic-"${{ steps.get_version.outputs.version-without-v }}"-x86_64-unknown-linux-gnu.tar.gz -C tmp/x86_64/ arctic
        tar -czvf arctic-"${{ steps.get_version.outputs.version-without-v }}"-aarch64-unknown-linux-gnu.tar.gz -C tmp/aarch64/ arctic
        cd tmp/arctic;tar -czvf ../../runtime-"$(jq -r '.core_version' main-info.json | awk '{print $1}')".tar.gz *;cd ../../
        echo "${{ steps.get_version.outputs.version-without-v }}" > version
        sha256sum *.tar.gz > sha256sum
        rm -rf tmp/

    - name: Upload assets to release
      uses: softprops/action-gh-release@v1
      with:
        name: arctic ${{ steps.get_version.outputs.version }}
        body: ${{ steps.gen_release_body.outputs.RELEASE_BODY }}
        files: ./release/*
        draft: true
