name: Release

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Release version tag'
        default: 'v0.1.0'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check to latest commit
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2022-01-16
          components: rustfmt
          target: wasm32-unknown-unknown
          default: true
      - name: Test and Build optimized binary
        run: |
          cargo test --all
          cargo clean
          cargo build --release
      - uses: actions/upload-artifact@v2
        with:
          name: ice-node
          path: target/release/ice-node

  release:
    name: Release project
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download ICE project content
        uses: actions/download-artifact@v2
        with: 
          name: ice-node
      - name: Archive project content
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'ice-node.zip'
      - name: Create Github release
        id: create-new-release
        uses: actions/create-release@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          tag_name: ${{ github.event.inputs.release-version }}
          release_name: Frost Testnet Release ${{ github.event.inputs.release-version }}
      - name: Upload asset to Github release
        uses: actions/upload-release-asset@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./ice-node.zip
          asset_name: ice-node-${{ steps.version.outputs.tag_name }}.zip
          asset_content_type: application/zip
